"""
test_emotional_llm.py - TDD for emotional message classification.

These tests call the actual GPT-4o-mini classifier to verify emotional
message routing. They are integration tests that require an OpenAI API
key and network access.

Run with: pytest tests/test_emotional_llm.py -v -m integration

# ============================================================================
# EMOTIONAL MESSAGES SPECIFICATION (Single Source of Truth)
#
# This comment defines the complete expected behavior of Dugri's emotional
# message classification. When behavior changes, UPDATE THIS COMMENT FIRST,
# then update/add tests, then fix code to pass.
#
# ============================================================================
#
# Dugri is not a therapist. Two sub-flows handle emotional content:
#
# 1. STANDALONE EMOTIONAL: User shares emotions as the main content,
#    with no habit action embedded.
#    - Examples: "אני מרגיש רע", "יש לי חרדות", "יום קשה", "אין לי כוח"
#    - Emotional questions without data ask: "למה אני אוכל כל כך הרבה?"
#    - classifier: type=emotional, empathy_reflection=LLM-generated one-liner
#    - handler: empathy_reflection + boundary + CTA (see EMOTIONAL SUPPORT
#      MODES below)
#    - NOT emotional: "אין לי כוח לבשל" (food context), "יום קשה, אכלתי
#      הרבה" (meal with emotional context)
#    - emotional overrides active toggle flows when emotion is the main
#      content
#
# 2. ACTION WITH EMOTIONAL CONTEXT: User logs a habit but expresses
#    emotion alongside it.
#    - Examples: "אכלתי המון כי אני עצוב" (meal), "הלכתי לישון מאוחר,
#      הרגשתי חרדה" (sleep)
#    - classifier: type stays as the action type (meal/sleep/etc.),
#      emotional_context=true, empathy_reflection=LLM-generated one-liner
#    - handler: prepends empathy_reflection to the normal response
#    - The action is processed normally (food logged, sleep logged, etc.)
#
# DUGRI'S EMOTIONAL LOGIC:
#    As long as the user logs any action (food, drink, sleep, workout, self-care)
#    even with emotions, Dugri cooperates: logs the entry + adds empathy.
#    Only when the message is PURE emotion (no specific action to log) does
#    Dugri offer emotional support (mode-dependent, see below).
#    This applies regardless of how many emotional messages appear in history -
#    each message is classified by its own content, independently.
#
# EMPATHY REFLECTION (empathy_reflection field):
#    - One liner Carl Rogers empathy type response, specific to what the user said
#    - Generated by the classifier LLM for both emotional and emotional_context
#    - Examples: "נשמע שאתה מרגיש אשמה על זה", "נשמע שזה מעיק עליך"
#    - Used instead of static empathy pools for personalized response
#
# EMOTIONAL SUPPORT MODES (config: emotional_support.mode):
#
#    MODE "creator" (default):
#       Dugri says he's not built for emotions, but offers to connect
#       the user with Shai, his creator, who is an experienced therapist.
#       Button: URL deep link to t.me/{creator_telegram_username}.
#       No GPT prompt is built. No callback handler fires.
#
#    MODE "chatgpt" (legacy, disabled by default):
#       Dugri offers to build a personalized ChatGPT prompt with 7 days
#       of habit data. Button: callback -> builds prompt -> shows copy
#       block + "Open ChatGPT" URL button.
#
# ============================================================================
"""

import os
import sys
import pytest

# Add project root and tests dir to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.dirname(__file__))

from _lazy_optin_helpers import (
    _make_analyzer, _build_toggle_state, _build_history, _classify,
    llm_judge,
)

pytestmark = pytest.mark.integration


class TestEmotionalClassification:
    """Emotional messages and emotional context on actions."""

    def test_pure_emotional_message(self):
        """Pure emotional message -> type=emotional."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אני מרגיש רע")
        assert result.type == "emotional"

    def test_emotional_distress(self):
        """Distress message -> type=emotional."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "יש לי חרדות")
        assert result.type == "emotional"

    def test_emotional_question_no_data_ask(self):
        """Emotional question without data ask -> emotional, not answer_question."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "למה אני אוכל כל כך הרבה?")
        assert result.type == "emotional"

    def test_vague_eating_with_emotion_is_emotional(self):
        """'אכלתי המון כי אני עצוב' - no specific food -> emotional, not meal.

        There's nothing concrete to log. 'המון' is not a food item.
        """
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אכלתי המון כי אני עצוב")
        assert result.type == "emotional"

    def test_specific_food_with_emotion_is_meal(self):
        """'אכלתי גלידה כי אני עצוב' - specific food -> meal with emotional_context."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אכלתי גלידה כי אני עצוב")
        assert result.type == "meal"
        assert result.emotional_context is True
        assert result.meal is not None

    def test_angry_about_eating_is_meal_with_empathy(self):
        """'אני כועס על עצמי שאכלתי גלידה' -> meal + emotional_context + empathy_reflection.

        This is a food entry with emotional context - should log the meal AND
        provide empathy, but NOT offer ChatGPT/boundary messages.
        """
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אני כועס על עצמי שאכלתי גלידה עכשיו")
        assert result.type == "meal"
        assert result.emotional_context is True
        assert result.empathy_reflection
        assert len(result.empathy_reflection) > 5
        # Should have food data
        assert result.meal is not None

    def test_bummed_about_drinking_coffee_is_meal_with_empathy(self):
        """'מבואס על עצמי ששתיתי קפה עם חלב שקדים' -> meal + emotional_context + empathy.

        Prod regression: this was classified as emotional and food was NOT logged.
        Must be meal with emotional_context - the drink is concrete food.
        """
        analyzer = _make_analyzer()
        result = _classify(analyzer, "מבואס על עצמי ששתיתי עכשיו קפה עם חלב שקדים")
        assert result.type == "meal"
        assert result.emotional_context is True
        assert result.empathy_reflection
        assert result.meal is not None
        assert len(result.meal.groups) > 0

    def test_repeated_food_with_emotion_stays_meal(self):
        """5th food+emotion message must still be meal even after 4 prior rounds.

        Dugri logic: as long as user logs food (even with emotions), Dugri cooperates -
        logs the entry + adds empathy. Only pure emotion (no food) triggers GPT referral.
        The classifier must evaluate each message independently.
        History includes both user messages AND bot food+empathy responses.
        """
        user_msg = "מבואס על עצמי ששתיתי עוד כוס של קפה עם חלב שקדים"
        bot_response = "נשמע שאתה קשה עם עצמך על זה.\n\n☕ קפה עם חלב שקדים\n~15 קל׳ | 0g חלבון\n\n✅ נרשם"
        analyzer = _make_analyzer()
        result = _classify(
            analyzer, user_msg,
            history=_build_history(
                ("user", user_msg),
                ("bot", bot_response),
                ("user", user_msg),
                ("bot", bot_response),
                ("user", user_msg),
                ("bot", bot_response),
                ("user", user_msg),
                ("bot", bot_response),
            ),
        )
        assert result.type == "meal"
        assert result.emotional_context is True
        assert result.meal is not None
        assert result.meal.groups[0].total_calories > 0
        assert result.meal.groups[0].total_protein >= 0

    def test_food_emotion_after_emotional_boundary_in_history(self):
        """Food+emotion must stay meal even when history contains an emotional boundary.

        Production regression: after first correct classification (meal+empathy),
        if the classifier once misclassified as emotional and the boundary response
        entered history, subsequent identical messages also got misclassified.
        The classifier must evaluate each message independently.
        """
        user_msg = "מבואס על עצמי ששתיתי קפה עם חלב שקדים"
        food_response = "נשמע שאתה קשה עם עצמך על זה.\n\n☕ קפה עם חלב שקדים\n~15 קל׳ | 0g חלבון\n\n✅ נרשם"
        emotional_boundary = "נשמע שזה מעיק עליך.\n\nאני פה בשביל לעקוב אחרי ההרגלים שלך. לשיחה רגשית יותר מעמיקה, אפשר לנסות את ChatGPT."
        analyzer = _make_analyzer()
        result = _classify(
            analyzer, user_msg,
            history=_build_history(
                ("user", user_msg),
                ("bot", food_response),
                ("user", user_msg),
                ("bot", emotional_boundary),
            ),
        )
        assert result.type == "meal"
        assert result.emotional_context is True
        assert result.meal is not None

    def test_sleep_with_emotion_is_sleep(self):
        """Sleep + emotion -> sleep with emotional_context=True."""
        analyzer = _make_analyzer()
        result = _classify(
            analyzer, "הלכתי לישון ב-2 בלילה, הרגשתי חרדה",
            toggle_state=_build_toggle_state(sleep="active"),
        )
        assert result.type == "sleep"
        assert result.emotional_context is True

    def test_informational_question_not_emotional(self):
        """Data question -> answer_question, not emotional."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "כמה קלוריות אכלתי השבוע?")
        assert result.type == "answer_question"

    def test_no_energy_to_cook_is_meal(self):
        """Food context with 'no energy' -> meal, not emotional."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אין לי כוח לבשל אז הזמנתי פיצה")
        assert result.type == "meal"

    def test_emotional_overrides_offered_toggle(self):
        """Emotional message during offered toggle -> emotional, not conversation_reply."""
        analyzer = _make_analyzer()
        result = _classify(
            analyzer, "אני בדיכאון",
            toggle_state=_build_toggle_state(sleep="offered"),
            history=_build_history(
                ("bot", "אני יכול לעקוב גם אחרי שעת השינה שלך. מעניין?"),
            ),
        )
        assert result.type == "emotional"

    def test_empathy_reflection_on_pure_emotional(self):
        """Pure emotional message -> empathy_reflection filled with specific reflection."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אני מרגיש רע מאוד היום")
        assert result.type == "emotional"
        assert result.empathy_reflection
        assert len(result.empathy_reflection) > 5
        # Should NOT be generic - should reflect the specific feeling
        assert llm_judge(
            "Does this text specifically reflect or acknowledge feeling bad, having a hard time, or emotional distress?",
            result.empathy_reflection,
        ), f"Expected specific empathy reflection, got: {result.empathy_reflection}"

    def test_empathy_reflection_on_emotional_context_meal(self):
        """Meal with emotional context -> empathy_reflection filled."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אכלתי גלידה ואני שונא את עצמי")
        assert result.type == "meal"
        assert result.emotional_context is True
        assert result.empathy_reflection
        assert len(result.empathy_reflection) > 5

    def test_empathy_reflection_is_one_liner(self):
        """Empathy reflection should be a single short sentence."""
        analyzer = _make_analyzer()
        result = _classify(analyzer, "אני בדיכאון כבר שבוע")
        assert result.type == "emotional"
        assert result.empathy_reflection
        # One liner - no newlines, reasonable length
        assert "\n" not in result.empathy_reflection
        assert len(result.empathy_reflection) < 100
